name: hello-world
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello from Job 1!"

  job2:
    runs-on: ubuntu-latest
    needs: job1   
    steps:
      - name: Step 2
        run: echo "This is Job 2, which depends on Job 1"
